/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class FormRecordObtenidos extends javax.swing.JPanel  {

    
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form FormRecordObtenidos
     */
    public FormRecordObtenidos() {
        initComponents();
        iniTabla();
        confiTabla();
    }

    private void confiTabla() {
        //Color de la tabla
        tablaRecords.setOpaque(true);
        tablaRecords.setFillsViewportHeight(true);
        tablaRecords.setBackground(Color.WHITE);
        
        //Lineas horizontales
        tablaRecords.setShowVerticalLines(false);
        tablaRecords.setShowHorizontalLines(true);
        tablaRecords.setGridColor(Constantes.COLOR_BEIGE);
        
        //Pintar encabezado de la tabla y centrar el texto
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer(){};
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        headerRenderer.setBackground(Constantes.COLOR_MEDIO);
        
        for (int i = 0; i < tablaRecords.getModel().getColumnCount(); i++) {
            tablaRecords.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        tablaRecords.getTableHeader().setPreferredSize(new Dimension(100, 40));
        
        //Pintar encabezado de la tabla y centrar el texto
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer(){};
        cellRender.setHorizontalAlignment(JLabel.CENTER);
        
        for (int i = 0; i < tablaRecords.getModel().getColumnCount(); i++) {
            tablaRecords.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        }
        
        //Esquina superior derecha del jscrollpane, sin este código, hay un cuadro color gris
        JPanel panelEsquina = new JPanel();
        panelEsquina.setBackground(Constantes.COLOR_MEDIO);
        jScrollPane2.setCorner(JScrollPane.UPPER_RIGHT_CORNER, panelEsquina);
   }
    
    /*Método para crear el modelo de la tabla*/
    private void iniTabla() {
        modeloTabla = new DefaultTableModel(new String[]{"Fecha", "Trabajador",
            "Cliente", "Tiempo trabajado", "Comisión", "Descuento", "Sueldo obtenido"}, 40) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        //Encabezado
        tablaRecords.setModel(modeloTabla);

        //Ancho de algunas columnas
//        tablaRecords.getColumnModel().getColumn(0).setMinWidth(50);
//        tablaRecords.getColumnModel().getColumn(3).setMinWidth(60);
//        tablaRecords.getColumnModel().getColumn(4).setMinWidth(10);

        //Altura de las filas
        tablaRecords.setRowHeight(30);

        //Ajustar contenido
        tablaRecords.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        modeloTabla.setRowCount(0);
        for (int i = 0; i < 30; i++) {
            Object[] registro = {"Fecha "+i, "Trabajador "+i,
            "Cliente "+i, "Tiempo trabajado "+i, "Comisión "+i, "Descuento "+i, "Sueldo obtenido "+i};
            modeloTabla.addRow(registro);
        }
        
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRecords = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(650, 450));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Constantes.COLOR_BEIGE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(Constantes.COLOR_LIGERO);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Records obtenidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(Constantes.COLOR_BEIGE);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 10, 30));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 153, 51));
        jScrollPane2.setBorder(null);

        tablaRecords.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaRecords.setToolTipText(null);
        tablaRecords.setGridColor(new java.awt.Color(0, 0, 0));
        tablaRecords.setRowHeight(30);
        tablaRecords.setSelectionBackground(Constantes.COLOR_PRIMARIO);
        tablaRecords.setShowVerticalLines(false);
        tablaRecords.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaRecords);

        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaRecords;
    // End of variables declaration//GEN-END:variables
}
