/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.Icon;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class MenuItem extends javax.swing.JPanel {
    
    /** Creates new form MenuItem */
    public MenuItem(Icon ico, String nomb) {
        initComponents();
        initMenu(ico, nomb);
        setName(nomb);
    }
    
    private void initMenu(Icon ico, String nomb){
        icono.setIcon(ico);
        nombre.setText(nomb);
    }
    
    public void setColor(){
        this.setBackground(Constantes.COLOR_BEIGE);
    }
    
    public void resetColor(){
        this.setBackground(Constantes.COLOR_LIGERO);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();

        setBackground(Constantes.COLOR_LIGERO);
        setMaximumSize(new java.awt.Dimension(2147483647, 60));
        setPreferredSize(new java.awt.Dimension(200, 60));
        setLayout(new java.awt.BorderLayout());

        icono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        icono.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        icono.setPreferredSize(new java.awt.Dimension(60, 0));
        add(icono, java.awt.BorderLayout.LINE_START);

        nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre.setForeground(Constantes.COLOR_PRIMARIO);
        add(nombre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icono;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

}
