/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controladores.ControladorGeneral;
import controladores.ControladorMenu;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import jiconfont.swing.IconFontSwing;
import recursos.iconos.GoogleMaterialDesignIcons;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class PanelTrabajadorLayout extends javax.swing.JPanel {

    private TrabajadorTemporizador temporizadorTrabajador;
    public static List<FormTrabajador> listaFormTrabajadores;
    public static boolean activarBotones = false;
    private boolean jornadaDetenida = false;

    //Efecto del botón registrar que cambie de color, para destacarlo que ya se puede presionar
    public static Timer destacarBoton;

    //Fecha
    public static Date fecha;
    private String formato;
    DateFormat sdf;

    //Variable para sabaer si los empleados ya han sido guardados
    public static boolean yaFueronGuardados = false;

    //Controlador general
    ControladorGeneral ctrlGeneral;

    /**
     * Creates new form NewJPanel
     */
    public PanelTrabajadorLayout() {
        iniDestacarBotonRegistrarTimer();
        initFecha();
        initComponents();
        pintarIconos();
        pintarFormTrabajador();

        //Temporizador icono y tiempo en la vista
        temporizadorTrabajador = new TrabajadorTemporizador(lblContadorTiempo, lblMensaje, listaFormTrabajadores);

        ctrlGeneral = new ControladorGeneral();
    }

    /*Inicializar el timer que funciona para destacar el botón registrar,
        cuando los trabajdores han terminado su jornada ya se puede registrar la información*/
    private void iniDestacarBotonRegistrarTimer() {
        PanelTrabajadorLayout.destacarBoton = new Timer(1000, new ActionListener() {
            boolean var = false;

            @Override
            public void actionPerformed(ActionEvent e) {
                var = !var;
                if (var) {
                    panelRegistrar.setBackground(Constantes.COLOR_MEDIO);

                } else {
                    panelRegistrar.setBackground(Constantes.COLOR_PRIMARIO);
                }
            }
        });
    }

    private void pintarIconos() {

        //Icono bandera
        jLabel1.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FLAG, 30, Color.WHITE));
        //Icono guardar
        jLabel3.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SAVE, 30, Color.WHITE));
        //Icono reloj
        lblRelojIcono.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SCHEDULE, 20, new Color(64, 63, 62)));
        //Icono detener
        btnDetenerIcono.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.BLOCK, 20, new Color(64, 63, 62)));
        btnDetenerIcono.setRolloverIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.BLOCK, 23, new Color(64, 63, 62)));
        //Icono informacion
        btnInfoIcono.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.INFO, 24, Constantes.COLOR_MEDIO));
        btnInfoIcono.setRolloverIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.INFO, 27, Constantes.COLOR_MEDIO));
    }

    private void pintarFormTrabajador() {
        listaFormTrabajadores = new ArrayList<>();
        for (int i = 1; i <= 3; i++) {
            FormTrabajador formTrabajador = new FormTrabajador(i);
            listaFormTrabajadores.add(formTrabajador);
            panelTrabajadores.add(formTrabajador);
        }
    }

    /*Variables utilizadas por el DateChooser, código personalizado dentro
        del código de netbeans*/
    private void initFecha() {
        sdf = new SimpleDateFormat("yyyy/MM/dd");
        try {
            fecha = sdf.parse(sdf.format(new Date()));
        } catch (ParseException ex) {
            Logger.getLogger(PanelTrabajadorLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
        formato = sdf.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser(fecha, formato);
        jLabel7 = new javax.swing.JLabel();
        txtJornada = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnInfoIcono = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelIniciarJornada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblContadorTiempo = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblRelojIcono = new javax.swing.JLabel();
        btnDetenerIcono = new javax.swing.JButton();
        panelTrabajadores = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(650, 450));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(Constantes.COLOR_BEIGE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(Constantes.COLOR_LIGERO);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Asignar trabajo");

        jDateChooser1.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jornada máxima:");

        txtJornada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJornada.setText("8");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "segundo(s)", "minuto(s)", "hora(s)" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setBorder(null);
        jComboBox1.setPreferredSize(new java.awt.Dimension(77, 24));

        btnInfoIcono.setToolTipText("Detener jornada");
        btnInfoIcono.setBorder(null);
        btnInfoIcono.setContentAreaFilled(false);
        btnInfoIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfoIcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoIconoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInfoIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnInfoIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(Constantes.COLOR_BEIGE);
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 150));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(Constantes.COLOR_BEIGE);

        panelIniciarJornada.setBackground(Constantes.COLOR_PRIMARIO);
        panelIniciarJornada.setPreferredSize(new java.awt.Dimension(150, 51));
        panelIniciarJornada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIniciarJornadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelIniciarJornadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelIniciarJornadaMouseExited(evt);
            }
        });
        panelIniciarJornada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelIniciarJornada.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 52, 51));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciar jornada");
        panelIniciarJornada.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 14, 90, 20));

        panelRegistrar.setBackground(Constantes.COLOR_PRIMARIO);
        panelRegistrar.setPreferredSize(new java.awt.Dimension(150, 51));
        panelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseExited(evt);
            }
        });
        panelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRegistrar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 52, 51));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar");
        panelRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 14, 90, 20));

        lblContadorTiempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblContadorTiempo.setText("00m 00s");

        lblMensaje.setToolTipText("");

        lblRelojIcono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRelojIcono.setToolTipText("");

        btnDetenerIcono.setToolTipText("Detener jornada");
        btnDetenerIcono.setBorder(null);
        btnDetenerIcono.setContentAreaFilled(false);
        btnDetenerIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetenerIcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerIconoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panelIniciarJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblRelojIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContadorTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetenerIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContadorTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnDetenerIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRelojIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelIniciarJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelTrabajadores.setBackground(Constantes.COLOR_BEIGE);
        panelTrabajadores.setPreferredSize(new java.awt.Dimension(650, 300));
        panelTrabajadores.setLayout(new java.awt.GridLayout(1, 3));
        add(panelTrabajadores, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void panelIniciarJornadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarJornadaMouseEntered
        panelIniciarJornada.setBackground(Constantes.COLOR_MEDIO);
    }//GEN-LAST:event_panelIniciarJornadaMouseEntered

    private void panelIniciarJornadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarJornadaMouseExited
        panelIniciarJornada.setBackground(Constantes.COLOR_PRIMARIO);
    }//GEN-LAST:event_panelIniciarJornadaMouseExited

    private void panelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseEntered
        panelRegistrar.setBackground(Constantes.COLOR_MEDIO);
    }//GEN-LAST:event_panelRegistrarMouseEntered

    private void panelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseExited
        panelRegistrar.setBackground(Constantes.COLOR_PRIMARIO);

    }//GEN-LAST:event_panelRegistrarMouseExited

    private void panelIniciarJornadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarJornadaMouseClicked

        //LocalDate date = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (TrabajadorTemporizador.timer.isRunning()) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Jornada en curso!", Constantes.COLOR_OK);
            return;
        } else if (!activarBotones) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Ingrese todos los campos!", Constantes.COLOR_ERROR);
            return;
        } else if (txtJornada.getText().isEmpty()) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Jornada vacía!", Constantes.COLOR_ERROR);
            return;
        } else if (Integer.valueOf(txtJornada.getText()) <= 5) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Jornada menor o igual que 5 " + jComboBox1.getSelectedItem() + "!", Constantes.COLOR_ERROR);
            return;
        }

        //Inicializamos la variable jornadaDetenida
        jornadaDetenida = false;

        //Configurar variables del temporizador, para que se ajusten al tiempo ingresado por el usuario
        TrabajadorTemporizador.jornada = Integer.valueOf(txtJornada.getText());
        TrabajadorTemporizador.multiplicador = (jComboBox1.getSelectedIndex() == 0)
                ? TrabajadorTemporizador.multiplicadorSegundos
                : (jComboBox1.getSelectedIndex() == 1)
                ? TrabajadorTemporizador.multiplicadorMinutos
                : TrabajadorTemporizador.multiplicadorHora;
        TrabajadorTemporizador.tiempoFinal = TrabajadorTemporizador.jornada * TrabajadorTemporizador.multiplicador;
        TrabajadorTemporizador.timerLoop = (TrabajadorTemporizador.multiplicador == TrabajadorTemporizador.multiplicadorHora) ? TrabajadorTemporizador.multiplicadorMinutos
                : (TrabajadorTemporizador.multiplicador == TrabajadorTemporizador.multiplicadorMinutos) ? TrabajadorTemporizador.multiplicadorSegundos : TrabajadorTemporizador.multiplicadorSegundos;

        //Si el color del botón registrar está "intermitente" lo detenemos y ponemos su color normal
        destacarBoton.stop();
        panelRegistrar.setBackground(Constantes.COLOR_PRIMARIO);

        //Comienza la jornada en un nuevo hilo
        new Thread(() -> {
            temporizadorTrabajador.empezarTemporizador();
        }).start();
    }//GEN-LAST:event_panelIniciarJornadaMouseClicked

    private void panelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseClicked
        if (TrabajadorTemporizador.temporizador == 0) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Los trabajadores no han iniciado!", Constantes.COLOR_ERROR);
            return;
        } else if (TrabajadorTemporizador.timer.isRunning()) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Espere que los trabajadores terminen!", Constantes.COLOR_ERROR);
            return;
        } else if (jornadaDetenida && !TrabajadorTemporizador.jornadasTerminadas) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Jornada detenida, no se puede guardar!", Constantes.COLOR_ERROR);
            return;
        }

        //Buscamos si alguno no ha sido guardado
        yaFueronGuardados = true;
        for (FormTrabajador formTrabajador : listaFormTrabajadores) {
            if (!formTrabajador.getEmpleadoGuardado()) {
                yaFueronGuardados = false;
                break;
            }
        }
        //Si ya todos fueron guardados
        if(yaFueronGuardados){
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Los registros ya fueron guardados!", Constantes.COLOR_ERROR);
        }
        
        
        //Si la fecha es null
        fecha = jDateChooser1.getDate();
        if (fecha == null) {
            ctrlGeneral.notificarMensaje(lblMensaje, 5000, "¡Fecha errónea!", Constantes.COLOR_ERROR);
            return;
        }
        
        //Registrar
        List<Thread> hilos = new ArrayList<>();
        
        //Iniciamos un hilo para cada formulario trabajdaor
        listaFormTrabajadores.forEach(formTrabajador -> {
            Thread thRegistrar = new Thread(() -> {
                formTrabajador.guardarEmpleado();
            }, "thRegistrar-"+formTrabajador.IDFORM);
            thRegistrar.start();
            hilos.add(thRegistrar);
        });
        
        //Esperamos todos los hilos
        for (Thread thread : hilos) {
            try {
                thread.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(PanelTrabajadorLayout.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //Actualizamos la tabla de registros
        ControladorMenu.ctrlRegistros.pintarTabla();
        System.out.println("Tabla de registros actualizada");
        
        //Si el botón registrar está intermitente lo detenemos
        if (destacarBoton.isRunning()) {
            destacarBoton.stop();
        }

    }//GEN-LAST:event_panelRegistrarMouseClicked

    private void btnDetenerIconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerIconoActionPerformed
        try {
            TrabajadorTemporizador.timer.stop();
            listaFormTrabajadores.forEach(formTrabajador -> {
                formTrabajador.timer.stop();
            });
            jornadaDetenida = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnDetenerIconoActionPerformed

    private void btnInfoIconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoIconoActionPerformed
        Runnable r = () -> {
            String html = "<html><body width='%1s'><h1>Información importante</h1>"
                    + "<p>Esta es la duración máxima del PROGRAMA, "
                    + "con propósitos simular rápidamente la jornada. "
                    + "<br><br>"
                    + "<p>"
                    + "Al guardar el registro se hará en horas.";
            int w = 200;

            JOptionPane.showMessageDialog(null, String.format(html, w, w), "Info", JOptionPane.INFORMATION_MESSAGE);
        };
        SwingUtilities.invokeLater(r);
    }//GEN-LAST:event_btnInfoIconoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetenerIcono;
    private javax.swing.JButton btnInfoIcono;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblContadorTiempo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblRelojIcono;
    private javax.swing.JPanel panelIniciarJornada;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPanel panelTrabajadores;
    private javax.swing.JTextField txtJornada;
    // End of variables declaration//GEN-END:variables

}
